// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresql

import (
	"database/sql"
)

type PaymentsrvKakao struct {
	Tid            string         `json:"tid"`
	Status         string         `json:"status"`
	Aid            sql.NullString `json:"aid"`
	PartnerOrderID string         `json:"partner_order_id"`
	PartnerUserID  string         `json:"partner_user_id"`
	ItemName       string         `json:"item_name"`
	Quantity       int32          `json:"quantity"`
	TotalAmount    int64          `json:"total_amount"`
	TaxFreeAmount  int64          `json:"tax_free_amount"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdateAt       sql.NullTime   `json:"update_at"`
	ApprovedAt     sql.NullTime   `json:"approved_at"`
}
